name: workshop

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses:
    - name: install_criterion.sh
      run: chmod 755 install_criterion.sh
      run: ./install_criterion.sh
    - name: make build
      run: make build
    - name: make build_test
      run: make build_test
