on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: bash install_criterion.sh

    - name: Run check
      run: make build_test

    - name: Run distcheck
      run: ./bin